"""
Raw model configuration data — strings and integers only, no heavy imports.

This module is imported by list_models.py (fast) and __init__.py (which
converts the data into full ModelConfig partials for training).
"""

# Entries: (name, max_context, has_processor, model_class, conv_type, kwargs, model_kwargs?)
# model_kwargs is optional dict passed to model_create_for_training partial
# (e.g., attn_implementation for qwen3_5 series). Omitted when empty.

MODEL_CONFIG_DATA = [
    # === OpenChat V3.2 (openchat / ConversationTemplate) ===
    ("llama", 4096, False, "LlamaForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4"}),
    ("llamaSplit", 4096, False, "LlamaSplitForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4"}),
    ("llamaLong", 32768, False, "LlamaLongForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4"}),
    ("llamaRing", 524288, False, "LlamaRingForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4"}),
    ("mistral", 8192, False, "MistralForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("mistralSplit", 8192, False, "MistralSplitForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("mistralLong", 32768, False, "MistralLongForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("mistralRing", 524288, False, "MistralRingForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("mixtral", 32768, False, "MixtralForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("mixtralRing", 524288, False, "MixtralRingForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("phi", 2048, False, "PhiForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("phi_ori", 2048, False, "OriPhiForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("gemma", 8192, False, "GemmaForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("gemmaRing", 524288, False, "GemmaRingForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("gemma2", 8192, False, "Gemma2ForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("qwen2", 32768, False, "Qwen2ForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("qwen2Ring", 524288, False, "Qwen2RingForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("qwen3", 32768, False, "Qwen3ForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("qwen3Ring", 524288, False, "Qwen3RingForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("qwen3Moe", 32768, False, "Qwen3MoeForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("qwen3MoeRing", 524288, False, "Qwen3MoeRingForCausalLM", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"}),
    ("qwen3_5", 262144, True, "Qwen3_5ForConditionalGeneration", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"},
     {"attn_implementation": "flash_attention_2"}),
    ("qwen3_5Moe", 262144, True, "Qwen3_5MoeForConditionalGeneration", "openchat",
     {"eot": "<|end_of_turn|>", "inference_condition": "GPT4 Correct"},
     {"attn_implementation": "flash_attention_2"}),

    # === Llama 3 (llama3 prompt format) ===
    ("llama3", 8192, False, "LlamaForCausalLM", "chatml",
     {"model": "llama", "prompt_format": "<|start_header_id|>{role}<|end_header_id|>\n\n{text}<|eot_id|>",
      "sep": "\n\n", "conv_sep": "", "inference_condition": "GPT4"}),
    ("llama3Ring", 524288, False, "LlamaRingForCausalLM", "chatml",
     {"model": "llama", "prompt_format": "<|start_header_id|>{role}<|end_header_id|>\n\n{text}<|eot_id|>",
      "sep": "\n\n", "conv_sep": "", "inference_condition": "GPT4"}),
    ("llama3.1", 131072, False, "LlamaLongForCausalLM", "chatml",
     {"model": "llama", "prompt_format": "<|start_header_id|>{role}<|end_header_id|>\n\n{text}<|eot_id|>",
      "sep": "\n\n", "conv_sep": "", "inference_condition": "GPT4"}),
    ("llama3.1Ring", 524288, False, "LlamaLongRingForCausalLM", "chatml",
     {"model": "llama", "prompt_format": "<|start_header_id|>{role}<|end_header_id|>\n\n{text}<|eot_id|>",
      "sep": "\n\n", "conv_sep": "", "inference_condition": "GPT4"}),

    # === ChatML (<|im_start|>) ===
    ("llama_chatml", 4096, False, "LlamaForCausalLM", "chatml",
     {"model": "llama", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4"}),
    ("llamaSplit_chatml", 4096, False, "LlamaSplitForCausalLM", "chatml",
     {"model": "llama", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4"}),
    ("llamaLong_chatml", 32768, False, "LlamaLongForCausalLM", "chatml",
     {"model": "llama", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4"}),
    ("llamaRing_chatml", 4096, False, "LlamaRingForCausalLM", "chatml",
     {"model": "llama", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4"}),
    ("mistral_chatml", 8192, False, "MistralForCausalLM", "chatml",
     {"model": "mistral", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("mistralSplit_chatml", 8192, False, "MistralSplitForCausalLM", "chatml",
     {"model": "mistral", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("mistralLong_chatml", 32768, False, "MistralLongForCausalLM", "chatml",
     {"model": "mistral", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("mistralRing_chatml", 8192, False, "MistralRingForCausalLM", "chatml",
     {"model": "mistral", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("mixtral_chatml", 32768, False, "MixtralForCausalLM", "chatml",
     {"model": "mixtral", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("mixtralRing_chatml", 524288, False, "MixtralRingForCausalLM", "chatml",
     {"model": "mixtral", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("phi_chatml", 2048, False, "PhiForCausalLM", "chatml",
     {"model": "phi", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("phi_ori_chatml", 2048, False, "OriPhiForCausalLM", "chatml",
     {"model": "phi", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("gemma_chatml", 8192, False, "GemmaForCausalLM", "chatml",
     {"model": "gemma_chatml", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("gemmaRing_chatml", 524288, False, "GemmaRingForCausalLM", "chatml",
     {"model": "gemma_chatml", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("gemma2_chatml", 8192, False, "Gemma2ForCausalLM", "chatml",
     {"model": "gemma2_chatml", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("qwen2_chatml", 32768, False, "Qwen2ForCausalLM", "chatml",
     {"model": "qwen2", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("qwen2Ring_chatml", 32768, False, "Qwen2RingForCausalLM", "chatml",
     {"model": "qwen2", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("qwen3_chatml", 32768, False, "Qwen3ForCausalLM", "chatml",
     {"model": "qwen3", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("qwen3Ring_chatml", 32768, False, "Qwen3RingForCausalLM", "chatml",
     {"model": "qwen3", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("qwen3Moe_chatml", 32768, False, "Qwen3MoeForCausalLM", "chatml",
     {"model": "qwen3Moe", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("qwen3MoeRing_chatml", 32768, False, "Qwen3MoeRingForCausalLM", "chatml",
     {"model": "qwen3Moe", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"}),
    ("qwen3_5_chatml", 262144, True, "Qwen3_5ForConditionalGeneration", "chatml",
     {"model": "qwen3_5", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"},
     {"attn_implementation": "flash_attention_2"}),
    ("qwen3_5Moe_chatml", 262144, True, "Qwen3_5MoeForConditionalGeneration", "chatml",
     {"model": "qwen3_5_moe", "prompt_format": "<|im_start|>{role}\n{text}<|im_end|>", "inference_condition": "GPT4 correct"},
     {"attn_implementation": "flash_attention_2"}),

    # === Gemma Instruct (native format) ===
    ("gemma_instruct", 8192, False, "GemmaForCausalLM", "chatml",
     {"model": "gemma", "prompt_format": "<start_of_turn>{role}\n{text}<end_of_turn>", "inference_condition": "GPT4 correct"}),
    ("gemmaRing_instruct", 524288, False, "GemmaRingForCausalLM", "chatml",
     {"model": "gemma", "prompt_format": "<start_of_turn>{role}\n{text}<end_of_turn>", "inference_condition": "GPT4 correct"}),
    ("gemma2_instruct", 8192, False, "Gemma2ForCausalLM", "chatml",
     {"model": "gemma2", "prompt_format": "<start_of_turn>{role}\n{text}<end_of_turn>", "inference_condition": "GPT4 correct"}),

    # === DeepSeek ===
    ("deepseekv2", 163840, False, "DeepseekV2ForCausalLM", "deepseek",
     {"prompt_format": {"user": "<｜{role}｜>{text}", "assistant": "<｜{role}｜>{text}<｜end▁of▁sentence｜>"}}),
    ("qwen2_deepseek", 32768, False, "Qwen2ForCausalLM", "deepseek",
     {"prompt_format": {"user": "<｜{role}｜>{text}", "assistant": "<｜{role}｜>{text}<｜end▁of▁sentence｜>"}}),
    ("qwen2Ring_deepseek", 32768, False, "Qwen2RingForCausalLM", "deepseek",
     {"prompt_format": {"user": "<｜{role}｜>{text}", "assistant": "<｜{role}｜>{text}<｜end▁of▁sentence｜>"}}),
    ("qwen3_deepseek", 32768, False, "Qwen3ForCausalLM", "deepseek",
     {"prompt_format": {"user": "<｜{role}｜>{text}", "assistant": "<｜{role}｜>{text}<｜end▁of▁sentence｜>"}}),
    ("qwen3Ring_deepseek", 32768, False, "Qwen3RingForCausalLM", "deepseek",
     {"prompt_format": {"user": "<｜{role}｜>{text}", "assistant": "<｜{role}｜>{text}<｜end▁of▁sentence｜>"}}),
    ("qwen3Moe_deepseek", 32768, False, "Qwen3MoeForCausalLM", "deepseek",
     {"prompt_format": {"user": "<｜{role}｜>{text}", "assistant": "<｜{role}｜>{text}<｜end▁of▁sentence｜>"}}),
    ("qwen3MoeRing_deepseek", 32768, False, "Qwen3MoeRingForCausalLM", "deepseek",
     {"prompt_format": {"user": "<｜{role}｜>{text}", "assistant": "<｜{role}｜>{text}<｜end▁of▁sentence｜>"}}),

    # === Zephyr ===
    ("zephyr", 8192, False, "MistralForCausalLM", "chatml",
     {"model": "mistral", "prompt_format": "<|{role}|>\n{text}</s>", "inference_condition": ""}),
]
